version: "3"

services:
  db:
    image: postgres:12.3-alpine
    restart: unless-stopped
    ports:
      - 5432:5432

    environment:
      POSTGRES_USER: passport_scorer
      POSTGRES_PASSWORD: passport_scorer_pwd
      POSTGRES_DB: passport_scorer
      PGDATA: /scorer_api_data

    volumes:
      - ./postgres_db_data:/scorer_api_data

  scorer:
    build: .
    restart: unless-stopped
    env_file: .env

    ports:
      - 8002:8002
