name: Cypress Tests

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      commit:
        description: "Commit ref"
        required: true
        type: string

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python "3.10"
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install pipenv
        run: pip3 install pipenv

      - name: Setup backend
        working-directory: ./api
        run: |
          pipenv requirements --dev > requirements.txt
          pip3 install -r requirements.txt
          python manage.py migrate

      # - name: Build and run the api
      #   working-directory: ./api
      #   run: |
      #     gunicorn -w 4 -k uvicorn.workers.UvicornWorker scorer.asgi:application &

      - name: Install Interface Dependencies
        working-directory: ./interface
        run: yarn && yarn build

      - name: Run Cypress tests
        uses: cypress-io/github-action@v5
        with:
          working-directory: ./test
          start: |
            yarn start:api
            yarn start:ui
          wait-on: "http://localhost:3000, http://localhost:8002"
          # config: 'baseUrl=http://localhost:8000'

      # - name: Upload test results
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: test-results
      #     path: cypress/results
