name: Deploy Interface to Production
on:
  workflow_dispatch:
    inputs:
      # commit hash (for frontend deploy to Amplify)
      commit:
        description: "Branch/Commit ref"
        default: "origin/main"
        type: string
jobs:
  ui-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install UI dependencies
        working-directory: ./interface
        run: yarn --frozen-lockfile && yarn build

      - name: Run tests
        working-directory: ./interface
        run: yarn test

  cypress-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python "3.10"
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install pipenv
        run: pip3 install pipenv

      - name: Setup backend
        working-directory: ./api
        run: |
          pipenv requirements --dev > requirements.txt
          pip3 install -r requirements.txt
          python manage.py migrate

      - name: Setup UI
        working-directory: ./interface
        run: yarn --frozen-lockfile && yarn build

  deploy-app:
    needs: [ui-test, cypress-test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Checkout production-interface
        run: |
          git fetch
          git checkout -b production-interface origin/production-interface
          git reset --hard ${{ github.event.inputs.commit }}
          git remote set-url origin https://${{ secrets.GITHUB_TOKEN }}@github.com/gitcoinco/passport-scorer.git
          git push origin production-interface -f
