name: Deploy Interface to Staging
on:
  workflow_dispatch:
    inputs:
      commit:
        description: "Branch/Commit ref"
        default: "origin/main"
        type: string
jobs:
  deploy-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Checkout staging-interface
        run: |
          git fetch
          git checkout -b staging-interface origin/staging-interface
          git reset --hard ${{ github.event.inputs.commit }}
          git remote set-url origin https://${{ secrets.GITHUB_TOKEN }}@github.com/gitcoinco/passport-scorer.git
          git push origin staging-interface -f
