name: CI - WIP for 972

on:
  workflow_dispatch:
    inputs:
      commit:
        description: "Commit ref"
        required: true
        type: string

  push:
    branches: [972-implement-blocknative]

jobs:
  cypress-test:
    runs-on: ubuntu-latest
    steps:
      - name: Install linux deps
        run: |
          sudo apt-get install --no-install-recommends -y \
          fluxbox \
          xvfb

      - name: Install Interface Dependencies
        working-directory: ./interface
        run: yarn --frozen-lockfile && yarn build

      - name: Run Cypress tests
        uses: cypress-io/github-action@v5
        with:
          working-directory: ./test_syn
          start: |
            yarn start:api
            yarn start:ui
          wait-on: "http://127.0.0.1:3000,http://127.0.0.1:8000/health/"
          record: true
          command: yarn test:e2e:local
          headed: true
        env:
          NEXT_PUBLIC_PASSPORT_SCORER_ALCHEMY_API_KEY: ${{ secrets.NEXT_PUBLIC_PASSPORT_SCORER_ALCHEMY_API_KEY }}
          config: "baseUrl=http://localhost:8000"
          # pass the Cypress Cloud record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # pass GitHub token to allow accurately detecting a build vs a re-run build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISPLAY: :0.0
