name: Deploy API to Production

on:
  workflow_dispatch:
    inputs:
      commit:
        description: "Commit ref"
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo Hi
